default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: vagrant
  password:

development:
  <<: *default
  database: trailblazed-rails_development

test:
  <<: *default
  database: trailblazed-rails_test